### PR TITLE
twoliter: fix sdk inspect handling

### LINKED ISSUE #284: twoliter treats SDK images as if they were a kit
Develop cannot build Bottlerocket

```
Error: failed to inspect manifest of resource at public.ecr.aws/bottlerocket/bottlerocket-sdk:v0.41.0
```

### PR DESCRIPTION
**Pull request by jmt-lab**
**Description of changes:**

Fixes issue with locked image trying to inspect manifest for sdk

Closes #284
**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by webern — APPROVED** [review]

**Comment by jmt-lab** [comment]
run_test.sh does
```bash
cargo run -p twoliter --bin twoliter -- $@ --project-path /home/fedora/twoliter/tests/projects/local-kit/Twoliter.toml
```

```
[fedora@ip-172-31-32-163 twoliter]$ ./run_test.sh update
   Compiling twoliter v0.2.0 (/home/fedora/twoliter/twoliter)
   Compiling buildsys v0.1.0 (/home/fedora/twoliter/tools/buildsys)
   Compiling pubsys v0.1.0 (/home/fedora/twoliter/tools/pubsys)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 46.18s
     Running `target/debug/twoliter update --project-path /home/fedora/twoliter/tests/projects/local-kit/Twoliter.toml`
[fedora@ip-172-31-32-163 twoliter]$ ./run_test.sh fetch --arch aarch64
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/twoliter fetch --arch aarch64 --project-path /home/fedora/twoliter/tests/projects/local-kit/Twoliter.toml`
./run_test.sh build kit core-kit --arch aarch64
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/twoliter build kit core-kit --arch aarch64 --project-path /home/fedora/twoliter/tests/projects/local-kit/Twoliter.toml`
[cargo-make] INFO - cargo make 0.37.12
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Build File: /home/fedora/twoliter/tests/projects/local-kit/build/tools/Makefile.toml
[cargo-make] INFO - Task: build-kit
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: check-cargo-version
[cargo-make] INFO - Running Task: setup
[cargo-make] INFO - Running Task: setup-build
[cargo-make] INFO - Running Task: fetch-sdk
[cargo-make] INFO - Running Task: fetch-sources
[cargo-make] INFO - Running Task: fetch-vendored
go: no dependencies to vendor
[cargo-make] INFO - Running Task: publish-setup
17:08:39 [INFO] No infra config at '/home/fedora/twoliter/tests/projects/local-kit/Infra.toml' - using local roles/keys
[cargo-make] INFO - Running Task: cargo-metadata
[cargo-make] INFO - Running Task: build-kit
ManifestParse
   Compiling pkg-a-1_27 v0.1.0 (/home/fedora/twoliter/tests/projects/local-kit/packages/pkg-a-1.27)
   Compiling core-kit v0.1.0 (/home/fedora/twoliter/tests/projects/local-kit/kits/core-kit)
    Finished `dev` profile [optimized] target(s) in 12.43s
[cargo-make] INFO - Build Done in 16.65 seconds.

```

**Review by webern — DISMISSED** [review]
CI reveals a similar issue (or the same issue) as the one being fixed... also, I think maybe I was seeing this transiently locally yesterday?

```
called `Result::unwrap()` on an `Err` value: failed to inspect manifest of resource at public.ecr.aws/bottlerocket/bottlerocket-sdk:v0.41.0
```

File: twoliter/src/lock.rs [hunk 1]
```diff
@@ -54,9 +54,17 @@ pub(crate) struct LockedImage {
...
+
+    pub async fn new_sdk(vendor: &Vendor, image: &Image) -> Result<Self> {
+        Self::create("image", vendor, image).await
+    }
+
+    async fn create(item: &str, vendor: &Vendor, image: &Image) -> Result<Self> {
         let source = format!("{}/{}:v{}", vendor.registry, image.name, image.version);
         let manifest_bytes = docker!(
-            ["manifest", "inspect", source.as_str()],
+            [item, "inspect", source.as_str()],
```
Comment (bcressey) [inline twoliter/src/lock.rs]: We need to emit a more detailed error message, right now we just get "failed to inspect ..." with no additional output.

**Review by sam-berning — APPROVED** [review]

**Review by bcressey — APPROVED** [review]
