### PR TITLE
buildsys: avoid trailing slash for cache lookup

### LINKED ISSUE #158: blobs can't be fetched from the lookaside cache
I'm getting the following error when attempting to build Bottlerocket with the current tip of develop:
```
  ExternalFileFetch: Failed to fetch 'https://cache.bottlerocket.aws//acl-2.3.2.tar.gz/31aeb39958d8af5d08933dd3a89333a41025c3eb49fc461fa3c291caca51dad575ec13faeb7deba9b3c2ebf7615be7d45e2b78e50d4f83d8ec933c95931a7682/acl-2.3.2.tar.gz': 403 Forbidden
```

Note the doubled `//` in the URL path, which S3 won't like.

### PR DESCRIPTION
**Pull request by bcressey**
**Issue number:**

Closes #158

**Description of changes:**
The lookaside cache URL is now a `Url` and may have a trailing slash when formatted as a string. Appending a second slash could produce an invalid URL. Avoid this by using `Url::join` instead.

**Testing done:**
Built `aws-dev` and was able to retrieve missing blobs.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by webern — APPROVED** [review]
Ugh, that bug again (it took forever to get it right in tough and tuftool)

File: tools/buildsys/src/cache.rs [hunk 1]
```diff
@@ -72,7 +72,15 @@ impl LookasideCache {
...
-            let url = format!("{}/{}/{}/{}", self.lookaside_cache, name, hash, name);
+            let cache_key = format!("{}/{}/{}", name, hash, name);
+            let url = self
+                .lookaside_cache
+                .join(&cache_key)
+                .context(error::UrlJoinSnafu {
+                    path: cache_key,
+                    base: self.lookaside_cache.to_owned(),
+                })?
+                .to_string();
```
Comment (ecpullen) [inline tools/buildsys/src/cache.rs]: Was there a reason for this implementations vs the one below other than the extra error management?

```suggestion
           let url = self
                .lookaside_cache
                .join(&name)
                .context(error::UrlJoinSnafu {
                    path: name,
                    base: self.lookaside_cache.to_owned(),
                })?.join(&hash)
                .context(error::UrlJoinSnafu {
                    path: hash,
                    base: self.lookaside_cache.to_owned(),
                })?.join(&name)
                .context(error::UrlJoinSnafu {
                    path: name,
                    base: self.lookaside_cache.to_owned(),
                })?
                .to_string();
```

**Review by ecpullen — APPROVED** [review]

File: tools/buildsys/src/cache.rs (hunk 1 above)
Comment (bcressey) [reply tools/buildsys/src/cache.rs]: > Was there a reason for this implementations vs the one below other than the extra error management?

Mostly that, yeah. I poked around the url crate a bit and came up with what looks like a more idiomatic approach.

**Comment by bcressey** [comment]
Tested the above with the following:
```
# current setting works
BUILDSYS_LOOKASIDE_CACHE = "https://cache.bottlerocket.aws"

# trailing slash works
BUILDSYS_LOOKASIDE_CACHE = "https://cache.bottlerocket.aws/"

# repeated slash doesn't work
BUILDSYS_LOOKASIDE_CACHE = "https://cache.bottlerocket.aws//"
```

This seems like the right behavior to me - the first two are reasonable values that should be treated the same way, and the third is odd but might be wanted for a backend where every key is prefixed with a `/`.

**Review by ecpullen — APPROVED** [review]
